@startuml
danmuView -> DanmuController: adddanmuView()
DanmuController -> DanmuPoolManager: adddanmuView()
DanmuPoolManager -> DanmuProducer: adddanmuView()
DanmuProducer -> DanmuProducerPool: produce()
DanmuProducerPool -> DanmuPainter: exeecute()


@enduml