@startuml
DanmuView -> DanmuController: addDanmuView()
DanmuController -> DanmuPoolManager: addDanmuView()
DanmuPoolManager -> DanmuProducer: addDanmuView()
DanmuProducer -> DanmuProducerPool: produce()
DanmuProducerPool -> DanmuPainter: exeecute()


@enduml